### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by CodeWel** [jk08y/smart-yt-downloader#1]
![image](https://github.com/user-attachments/assets/360105f8-2757-4d05-acad-44238ac1d9b7)

**Comment by jk08y** [comment]
What error do you see in dev console? That can help  figure out the bug.

**Comment by CodeWel** [comment]
https://test.yt2be.com

**Comment by jk08y** [comment]
Yeah I see. I think we need to use an alternative way in the authentication method, and remove the dependency on cookies. Any idea on work through?

**Comment by CodeWel** [comment]
Hi. I’m not too sure how to fix this myself. If you want, I can share my server login details so you can check it out and make the changes. Let me know if that works for you.

**Comment by jk08y** [comment]
I'm on it, I'm sure we'll get it done.

**Comment by jk08y** [comment]
> 
> Hi. I’m not too sure how to fix this myself. If you want, I can share my server login details so you can check it out and make the changes. Let me know if that works for you.
> 
> 

Pushed an update on 'improved-version brach'. 
https://github.com/jk08y/smart-yt-downloader/tree/improved-version

Should be fine now.

**Comment by CodeWel** [comment]
![image](https://github.com/user-attachments/assets/2698c66e-f554-46f4-bfbd-d579f2491aa7)
